#!/bin/bash
#
# Environment for the Gaia DPAC module
#
# Location of DPAC commons (soft & docs)
export DPAC_HOME=$HOME/DPAC
#
# DPAC user
export DPAC_USER=mriello

# DPAC SVN
# ----------------------------------------------------------
export DPAC_SVN=http://gaia.esac.esa.int/dpacsvn/
export DPAC_TRUNK=$DPAC_SVN/DPAC
export DPAC_BRANCH=$DPAC_SVN/DPAC_branches
export DPAC_TAG=$DPAC_SVN/DPAC_tags
export DPAC_MINE=$DPAC_BRANCH/CU5/software/personal/$DPAC_USER

# DPCI & CU5 SVN
# ----------------------------------------------------------
export DPAC_PP=$DPAC_TRUNK/CU5/software/Photometry
export DPAC_DPCI=$DPAC_TRUNK/DPCI/software

# COMMONS
# ----------------------------------------------------------
# CU1 commons software
export SOFCOMMON=$DPAC_HOME/software/cu1common

# DPAC LaTeX document templates
export CU1DOCCOM=$DPAC_HOME/docs/cu1common

# CU5 LaTeX document templates
export CU5TEX=$DPAC_HOME/docs/cu5tex

# DPAC LaTeX
# ----------------------------------------------------------
DPAC_TEXMF=$DOCCOMMON/texmf
export BSTINPUTS=$DPAC_TEXMF/bibtex/bst:.:$BSTINPUTS
export TEXINPUTS=.:$DPAC_TEXMF/tex/:$CU5TEX:$TEXINPUTS
export BIBINPUTS=$DPAC_TEXMF/bibtex/bib:.:$BIBINPUTS

#
# Our Documentation tree
export DPAC_DOC=$HOME/Documents/DPAC
export CU5DOCS=$DPAC_DOC/CU5/SVN
export DPCIDOCS=$DPAC_DOC/DPCI/SVN

#
# Processing environment
export DPAC_SCRATCH=$HOME/GaiaScratch
export DPAC_SCRATCH_OPS=$DPAC_SCRATCH/Ops
export DPAC_SCRATCH_DATA=$DPAC_SCRATCH/Data
export DPAC_SCRATCH_TRUNK=$DPAC_SCRATCH/TRUNK

# DPAC Eclipse area
# ----------------------------------------------------------
# Default location for Eclipse workspaces
export DPAC_ECLIPSE=$DPAC_HOME/Eclipse
# Default location for IntelliJ projects
export DPAC_IDEA=$DPAC_HOME/IntelliJ
# Default set of DPCI core projects
export PROJ_CORE="DpciBaseline Echidna Scylla Charybdis"
# Default set of DPCI support projects
export PROJ_SUPPORT="Chimera Dtv DpciTests"
# Default set of PhotPipe projects
export PROJ_PHOTPIPE="DataTypeDefinitions Du04Catalogue Du04Cdb Du04Ingestion Du04Provenance Du04Scene Du11Background Du11Common Du11CrowdingEvaluation Du11Deblending Du11Decontamination Du11Straylight Du11TemplateLibrary Du14ExternalCalibration Du15Common Du15Phot Du15Spec Hydra PhotPipe PhotPipeBindings PhotPipeCore PhotPipeGraphics PhotPipeHadoop PhotPipeParent PhotPipeProcessing PhotPipePsf PhotPipeServices"
